apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --build local --profile gameprofile
    kompose.image-pull-policy: Never
    kompose.service.type: loadbalancer
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: caddy
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: caddy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --build local --profile gameprofile
        kompose.image-pull-policy: Never
        kompose.service.type: loadbalancer
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: caddy
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env
          image: caddy
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - curl -f http://localhost:80 || exit 1
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: caddy
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /var/log/caddy
              name: caddy-logs
      restartPolicy: Always
      volumes:
        - name: caddy-logs
          persistentVolumeClaim:
            claimName: caddy-logs
