FROM python:3.10

WORKDIR /app

# Kopiere requirements und installiere
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Kopiere den restlichen Code
COPY . .

# Setze den Port für Django
EXPOSE 8000

# Standardbefehl
CMD ["python", "manage.py", "runserver", "0.0.0.0:8001"]
