FROM nginx:alpine

# Eigene nginx.conf
#COPY nginx.conf /etc/nginx/nginx.conf
#COPY ./src/nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/nginx.conf /etc/nginx/nginx.conf



# Statisches Frontend kopieren:
COPY ft_transcendence_frontend/index.html /usr/share/nginx/html/
COPY ft_transcendence_frontend/css /usr/share/nginx/html/css
COPY ft_transcendence_frontend/js /usr/share/nginx/html/js

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
