FROM prom/prometheus:v3.2.1


COPY config/prometheus.yml /etc/prometheus/prometheus.yml

EXPOSE 9090

ENTRYPOINT ["/bin/prometheus"]
CMD ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus"]

#  docker run --name prometheus -d -p 127.0.0.1:9090:9090 prom/prometheus