FROM prom/prometheus:v3.2.1

COPY config/prometheus.yml /etc/prometheus/prometheus.yml
COPY config/rules.yaml /etc/prometheus/rules.yaml
COPY config/alerts.yaml /etc/prometheus/alerts.yaml
COPY config/node_rules.yaml /etc/prometheus/config/node_rules.yaml

EXPOSE 9090

ENTRYPOINT ["/bin/prometheus"]
CMD ["--config.file=/etc/prometheus/prometheus.yml", \
		"--storage.tsdb.path=/prometheus", \
		"--storage.tsdb.retention.time=14d"]
