FROM prom/alertmanager:latest

COPY config/alertmanager.yml /etc/alertmanager/alertmanager.yml

EXPOSE 9093

# ENTRYPOINT [ "/bin/alertmanager" ]

# CMD ["--config.file=/etc/alertmanager/alertmanager.yml", "--web.external-url=http://laurent.pongbahnhof.de:9093/alertmanager" ]